version: '3'
services:

    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile.backend
        container_name: backend
        ports:
            - 5000:5000

    frontend:
        build: 
            context: ./frontend/nhl-app
            dockerfile: Dockerfile.frontend
        container_name: frontend
        ports: 
            - 3000:3000
        links:
            - backend